In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd "/content/drive/MyDrive/544 Project/"

Mounted at /content/drive
/content/drive/.shortcut-targets-by-id/1X1HQ_JbFBub59HaYyHz4gNN-B89ZOL7e/544 Project

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df1 = pd.read_excel("./Test/results.xlsx")
df1

,task,model,model_source,lora_path,total,valid,failed,correct,incorrect,accuracy_all,accuracy_valid,precision_yes,recall_yes,f1_yes,sc_n_samples
0,qa,Qwen/Qwen2.5-3B-Instruct,base,NaN,10000,10000,0,4962,5038,0.4962,0.4962,0.4000,0.0112,0.0217,NaN
1,qa,Qwen/Qwen2.5-3B-Instruct,lora,./Train/Qwen2.5-3B/LoRA/model,10000,10000,0,5022,4978,0.5022,0.5022,0.5392,0.0439,0.0812,NaN
2,qa,Qwen/Qwen2.5-3B-Instruct,sc-lora,./Train/Qwen2.5-3B/LoRA/model,10000,10000,0,5026,4974,0.5026,0.5026,0.5217,0.0864,0.1483,3.0
3,qa,google/gemma-3-4b-it,base,NaN,10000,10000,0,5012,4988,0.5012,0.5012,0.5013,0.8723,0.6367,NaN
4,qa,google/gemma-3-4b-it,lora,./Train/Gemma3-4B/LoRA/model,10000,10000,0,5012,4988,0.5012,0.5012,0.5293,0.0397,0.0739,NaN
5,qa,google/gemma-3-4b-it,sc-lora,./Train/Gemma3-4B/LoRA/model,10000,10000,0,4943,5057,0.4943,0.4943,0.4901,0.2323,0.3152,3.0
6,dialogue,Qwen/Qwen2.5-3B-Instruct,base,NaN,10000,10000,0,5869,4131,0.5869,0.5869,0.7039,0.3028,0.4234,NaN
7,dialogue,Qwen/Qwen2.5-3B-Instruct,lora,./Train/Qwen2.5-3B/LoRA/model,10000,10000,0,5870,4130,0.5870,0.5870,0.8250,0.2230,0.3510,NaN
8,dialogue,google/gemma-3-4b-it,sc-lora,./Train/Gemma3-4B/LoRA/model,10000,10000,0,5333,4667,0.5333,0.5333,0.5729,0.2691,0.3662,3.0
9,dialogue,google/gemma-3-4b-it,base,NaN,10000,9999,1,6125,3875,0.6125,0.6126,0.5890,0.7497,0.6597,NaN
10,dialogue,google/gemma-3-4b-it,lora,./Train/Gemma3-4B/LoRA/model,10000,10000,0,5204,4796,0.5204,0.5204,0.8567,0.0513,0.0968,NaN
11,dialogue,Qwen/Qwen2.5-3B-Instruct,sc-lora,./Train/Qwen2.5-3B/LoRA/model,10000,10000,0,5892,4108,0.5892,0.5892,0.7194,0.2952,0.4186,3.0
12,summarization,Qwen/Qwen2.5-3B-Instruct,base,NaN,10000,7064,2936,2975,7025,0.2975,0.4211,0.4240,0.4944,0.4565,NaN
13,summarization,Qwen/Qwen2.5-3B-Instruct,lora,./Train/Qwen2.5-3B/LoRA/model,10000,7076,2924,3629,6371,0.3629,0.5129,0.7000,0.0161,0.0315,NaN
14,summarization,google/gemma-3-4b-it,base,NaN,10000,7132,2868,3869,6131,0.3869,0.5425,0.5252,0.7567,0.6200,NaN
15,summarization,google/gemma-3-4b-it,lora,./Train/Gemma3-4B/LoRA/model,10000,7162,2838,3625,6375,0.3625,0.5061,0.0000,0.0000,0.0000,NaN
16,summarization,Qwen/Qwen2.5-3B-Instruct,sc-lora,./Train/Qwen2.5-3B/LoRA/model,10000,10000,0,4610,5390,0.4610,0.4610,0.5729,0.2691,0.3662,3.0
17,summarization,google/gemma-3-4b-it,sc-lora,./Train/Gemma3-4B/LoRA/model,10000,10000,0,4876,5124,0.4876,0.4876,0.4898,0.4876,0.3841,3.0

In [11]:
df1.columns

Index(['task', 'model', 'model_source', 'lora_path', 'total', 'valid',
       'failed', 'correct', 'incorrect', 'accuracy_all', 'accuracy_valid',
       'precision_yes', 'recall_yes', 'f1_yes', 'sc_n_samples'],
      dtype='object')

In [12]:
df1 = df1[["task", "model", "model_source", "accuracy_all", "f1_yes"]]
df1

             task                     model model_source  accuracy_all  f1_yes
0              qa  Qwen/Qwen2.5-3B-Instruct         base        0.4962  0.0217
1              qa  Qwen/Qwen2.5-3B-Instruct         lora        0.5022  0.0812
2              qa  Qwen/Qwen2.5-3B-Instruct      sc-lora        0.5026  0.1483
3              qa      google/gemma-3-4b-it         base        0.5012  0.6367
4              qa      google/gemma-3-4b-it         lora        0.5012  0.0739
5              qa      google/gemma-3-4b-it      sc-lora        0.4943  0.3152
6        dialogue  Qwen/Qwen2.5-3B-Instruct         base        0.5869  0.4234
7        dialogue  Qwen/Qwen2.5-3B-Instruct         lora        0.5870  0.3510
8        dialogue      google/gemma-3-4b-it      sc-lora        0.5333  0.3662
9        dialogue      google/gemma-3-4b-it         base        0.6125  0.6597
10       dialogue      google/gemma-3-4b-it         lora        0.5204  0.0968
11       dialogue  Qwen/Qwen2.5-3B-Instruct      sc-lora        0.5892  0.4186
12  summarization  Qwen/Qwen2.5-3B-Instruct         base        0.2975  0.4565
13  summarization  Qwen/Qwen2.5-3B-Instruct         lora        0.3629  0.0315
14  summarization      google/gemma-3-4b-it         base        0.3869  0.6200
15  summarization      google/gemma-3-4b-it         lora        0.3625  0.0000
16  summarization  Qwen/Qwen2.5-3B-Instruct      sc-lora        0.4610  0.3662
17  summarization      google/gemma-3-4b-it      sc-lora        0.4876  0.3841

In [14]:
df2 = pd.read_excel("./Test/gc_results.xlsx")
df2

,task,generator,checker,gen_base_model,chk_base_model,model_source,max_rounds,total,valid,failed,...,avg_rounds,accuracy_all,accuracy_valid,precision_yes,recall_yes,f1_yes,detected,corrected,detection_rate,correction_rate
0,qa,gemma,qwen,google/gemma-3-4b-it,Qwen/Qwen2.5-3B-Instruct,gc-lora,1,2000,2000,0,...,1.84,0.4810,0.4810,0.4968,0.5315,0.5136,800,252,0.7759,0.3150
1,qa,qwen,gemma,Qwen/Qwen2.5-3B-Instruct,google/gemma-3-4b-it,gc-lora,1,2000,2000,0,...,1.00,0.4845,0.4845,0.0000,0.0000,0.0000,0,0,0.0000,0.0000
2,dialogue,gemma,qwen,google/gemma-3-4b-it,Qwen/Qwen2.5-3B-Instruct,gc-lora,1,2000,2000,0,...,1.12,0.4920,0.4920,0.8571,0.0175,0.0342,201,183,0.1950,0.9104
3,dialogue,qwen,gemma,Qwen/Qwen2.5-3B-Instruct,google/gemma-3-4b-it,gc-lora,1,2000,2000,0,...,1.00,0.4880,0.4880,1.0000,0.0068,0.0135,8,1,0.0078,0.1250
4,summarization,gemma,qwen,google/gemma-3-4b-it,Qwen/Qwen2.5-3B-Instruct,gc-lora,1,2000,1600,400,...,1.37,0.4140,0.5175,0.5957,0.1679,0.2620,527,390,0.5112,0.7400
5,summarization,qwen,gemma,Qwen/Qwen2.5-3B-Instruct,google/gemma-3-4b-it,gc-lora,1,2000,1789,211,...,1.00,0.4345,0.4857,0.3333,0.0011,0.0022,2,0,0.0019,0.0000

In [15]:
df2.columns

Index(['task', 'generator', 'checker', 'gen_base_model', 'chk_base_model',
       'model_source', 'max_rounds', 'total', 'valid', 'failed', 'correct',
       'incorrect', 'avg_rounds', 'accuracy_all', 'accuracy_valid',
       'precision_yes', 'recall_yes', 'f1_yes', 'detected', 'corrected',
       'detection_rate', 'correction_rate'],
      dtype='object')

In [16]:
df2 = df2[["task", "generator", "checker", "detection_rate", "correction_rate"]]
df2

            task generator checker  detection_rate  correction_rate
0             qa     gemma    qwen          0.7759           0.3150
1             qa      qwen   gemma          0.0000           0.0000
2       dialogue     gemma    qwen          0.1950           0.9104
3       dialogue      qwen   gemma          0.0078           0.1250
4  summarization     gemma    qwen          0.5112           0.7400
5  summarization      qwen   gemma          0.0019           0.0000